In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("Client_Project.csv")
df.head()

  Client_ID Bra_size Last_contact  Date_added Active_Dormant
0      C001     34DD        4/9/26    6/18/07        Dormant
1      C002     36DD       4/14/26   12/11/11        Dormant
2      C003      34C       4/14/26    9/29/08        Dormant
3      C004      32D        4/9/26    6/18/07        Dormant
4      C005      38I        4/9/26    6/18/07        Dormant

In [10]:
# 1. Total Clients

In [11]:
total_clients = len(df)
total_clients

325

In [12]:
# 2. Active vs Dormant

In [13]:
status_counts = df["Active_Dormant"].value_counts()
status_counts

Active     226
Dormant     99
Name: Active_Dormant, dtype: int64

In [14]:
# 3. Dormant Percentage

In [15]:
dormant_percentage = (df["Active_Dormant"].value_counts(normalize=True) * 100).round(2)
dormant_percentage

Active     69.54
Dormant    30.46
Name: Active_Dormant, dtype: float64

In [16]:
# 4. Most Common Bra Size

In [17]:
df["Bra_size"].value_counts().head(10)

34G      23
36DDD    20
34DDD    18
32DDD    18
34DD     16
36DD     15
32DD     14
38DD     14
32D      13
36D      12
Name: Bra_size, dtype: int64

In [18]:
# 5. Clients added by year

In [19]:
df["Date_added"] = pd.to_datetime(df["Date_added"])
df["Year_Added"] = df["Date_added"].dt.year
df["Year_Added"].value_counts().sort_index()

2007     15
2008      3
2009      5
2010      4
2011      4
2012      5
2013      5
2014      3
2015      2
2016      1
2017      3
2018      5
2019      2
2020      7
2021      8
2022      4
2023      4
2024     19
2025     21
2026    200
2027      1
2028      2
2029      2
Name: Year_Added, dtype: int64

In [20]:
# 6. Active/Dormant by year added

In [21]:
pd.crosstab(df["Year_Added"], df["Active_Dormant"])

Active_Dormant  Active  Dormant
Year_Added
2007                 0       15
2008                 0        3
2009                 0        5
2010                 0        4
2011                 0        4
2012                 0        5
2013                 0        5
2014                 0        3
2015                 0        2
2016                 0        1
2017                 0        3
2018                 0        5
2019                 0        2
2020                 0        7
2021                 0        8
2022                 0        4
2023                 0        4
2024                 0       19
2025                21        0
2026               200        0
2027                 1        0
2028                 2        0
2029                 2        0

In [25]:
df[df['Date_added'].dt.year >= 2027][
    ['Client_ID', 'Date_added']
]

    Client_ID Date_added
132      C133 2027-03-27
229      C230 2028-05-28
283      C284 2028-05-28
284      C285 2029-05-29
285      C286 2029-05-29

In [26]:
df.loc[[132,229,283,284,285]]

    Client_ID Bra_size Last_contact  Date_added Active_Dormant  Year_Added
132      C133      34G       5/28/26 2027-03-27         Active        2027
229      C230      36D       5/29/26 2028-05-28         Active        2028
283      C284    40DDD       5/29/26 2028-05-28         Active        2028
284      C285      40D       5/29/26 2029-05-29         Active        2029
285      C286      36D       5/29/26 2029-05-29         Active        2029

In [27]:
df.loc[df['Client_ID'] == 'C133', 'Date_added'] = '2026-03-27'
df.loc[df['Client_ID'].isin(['C230', 'C284']), 'Date_added'] = '2026-05-28'
df.loc[df['Client_ID'].isin(['C285', 'C286']), 'Date_added'] = '2026-05-29'
df['Date_added'] = pd.to_datetime(df['Date_added'])

In [28]:
df[df['Date_added'].dt.year >= 2027][
    ['Client_ID', 'Date_added']
]

Empty DataFrame
Columns: [Client_ID, Date_added]
Index: []

In [29]:
df['Date_added'].dt.year.value_counts().sort_index()

2007     15
2008      3
2009      5
2010      4
2011      4
2012      5
2013      5
2014      3
2015      2
2016      1
2017      3
2018      5
2019      2
2020      7
2021      8
2022      4
2023      4
2024     19
2025     21
2026    205
Name: Date_added, dtype: int64

In [30]:
# Check row count
print(len(df))

325

In [31]:
# Check for future dates
print(df[df['Date_added'].dt.year > 2026])

Empty DataFrame
Columns: [Client_ID, Bra_size, Last_contact , Date_added, Active_Dormant, Year_Added]
Index: []

In [32]:
# Check for duplicate client IDs
print(df['Client_ID'].duplicated().sum())

0

In [33]:
# Check for mising values
print(df.isnull().sum())

Client_ID         0
Bra_size          1
Last_contact      0
Date_added        0
Active_Dormant    0
Year_Added        0
dtype: int64

In [34]:
df[df['Bra_size'].isna()]

    Client_ID Bra_size Last_contact  Date_added Active_Dormant  Year_Added
271      C272      NaN       5/29/26 2026-03-10         Active        2026

In [36]:
df = pd.read_csv("client_crm.csv")

In [37]:
df[df['Bra_size'].isna()]

Empty DataFrame
Columns: [Client_ID, Bra_size, Last_contact , Date_added, Active_Dormant]
Index: []

In [38]:
print(df.isnull().sum())

Client_ID         0
Bra_size          0
Last_contact      0
Date_added        0
Active_Dormant    0
dtype: int64

In [39]:
print(len(df))

325

In [46]:
df =pd.read_csv("client_crm.csv", encoding="utf-8-sig")
df.to_csv("client_crm_mysql.csv", index=False, encoding="utf-8")

In [47]:
import os
print(os.listdir())

['.Rhistory', '.config', '.junie', 'Music', 'sales_analysis.ipynb', '.julia', '.zprofile.pysave', '.gitkraken', 'client_crm_utf8.csv', '.DS_Store', '.CFUserTextEncoding', 'javasharedresources', 'ace_adult_outcomes_analysis.ipynb', '.xonshrc', '.bashrc', '25_24_sales.ipynb', 'Client_Project.ipynb', '.zshrc', 'ace_project_sample.csv', '.local', '.mongodb', 'Pictures', '.zprofile', 'client_crm.csv', '.zsh_history', '.ipython', 'Desktop', 'Library', '.matplotlib', 'yearly_sales_trend.png', '.cups', '.bash_sessions', 'clean_25_24.csv', 'PycharmProjects', '.codex', 'Public', '.idlerc', '.tcshrc', '.vscode-R', '.RData', 'Movies', 'Applications', '.Rapp.history', '.Trash', 'Client_Project.csv', '.ipynb_checkpoints', '.jupyter', 'Documents', '.RDataTmp', '.mysql_history', '.vscode', '.spss', '.bash_profile', '.Xauthority', 'Downloads', '.python_history', '.continuum', '.cache', '.gitconfig', 'client_crm_mysql.csv', '.bash_history', '.viminfo', '.zsh_sessions', 'i86-Homebrew-install.sh', '.conda', 'PyCharmMiscProject']

In [48]:
print(df.head())
print(df.shape)

  Client_ID Bra_size Last_contact  Date_added Active_Dormant
0      C001     34DD        4/9/26    6/18/07        Dormant
1      C002     36DD       4/14/26   12/11/11        Dormant
2      C003      34C       4/14/26    9/29/08        Dormant
3      C004      32D        4/9/26    6/18/07        Dormant
4      C005      38I        4/9/26    6/18/07        Dormant
(325, 5)

In [50]:
print(df.columns)

Index(['Client_ID', 'Bra_size', 'Last_contact ', 'Date_added',
       'Active_Dormant'],
      dtype='object')

In [66]:
import pandas as pd

In [67]:
df = pd.read_csv("client_crm.csv", encoding="utf-8-sig")

In [68]:
# of clean columns
df.columns = df.columns.str.strip()

In [69]:
# convert dates
df['Last_contact'] = pd.to_datetime(df['Last_contact'])
df['Date_added'] = pd.to_datetime(df['Date_added'])

In [70]:
# save SQL-friendly file
df.to_csv("client_crm_mysql.csv", index=False, encoding="utf-8")

In [71]:
print(df[['Last_contact', 'Date_added']].head())

  Last_contact Date_added
0   2026-04-09 2007-06-18
1   2026-04-14 2011-12-11
2   2026-04-14 2008-09-29
3   2026-04-09 2007-06-18
4   2026-04-09 2007-06-18